/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as AccountsSlugRouteImport } from './routes/accounts.$slug'
import { Route as SettingsLlmRouteImport } from './routes/settings.llm'
import { Route as AccountsSlugIndexRouteImport } from './routes/accounts.$slug.index'
import { Route as AccountsSlugAskRouteImport } from './routes/accounts.$slug.ask'
import { Route as AccountsSlugCommitmentsRouteImport } from './routes/accounts.$slug.commitments'
import { Route as AccountsSlugCompareRouteImport } from './routes/accounts.$slug.compare'
import { Route as AccountsSlugImportRouteImport } from './routes/accounts.$slug.import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsSlugRoute = AccountsSlugRouteImport.update({
  id: '/accounts/$slug',
  path: '/accounts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLlmRoute = SettingsLlmRouteImport.update({
  id: '/settings/llm',
  path: '/settings/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsSlugIndexRoute = AccountsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsSlugRoute,
} as any)
const AccountsSlugAskRoute = AccountsSlugAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AccountsSlugRoute,
} as any)
const AccountsSlugCommitmentsRoute = AccountsSlugCommitmentsRouteImport.update({
  id: '/commitments',
  path: '/commitments',
  getParentRoute: () => AccountsSlugRoute,
} as any)
const AccountsSlugCompareRoute = AccountsSlugCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AccountsSlugRoute,
} as any)
const AccountsSlugImportRoute = AccountsSlugImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AccountsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/pipeline': typeof PipelineRoute
  '/accounts/$slug': typeof AccountsSlugRouteWithChildren
  '/settings/llm': typeof SettingsLlmRoute
  '/accounts/$slug/ask': typeof AccountsSlugAskRoute
  '/accounts/$slug/commitments': typeof AccountsSlugCommitmentsRoute
  '/accounts/$slug/compare': typeof AccountsSlugCompareRoute
  '/accounts/$slug/import': typeof AccountsSlugImportRoute
  '/accounts/$slug/': typeof AccountsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/pipeline': typeof PipelineRoute
  '/settings/llm': typeof SettingsLlmRoute
  '/accounts/$slug/ask': typeof AccountsSlugAskRoute
  '/accounts/$slug/commitments': typeof AccountsSlugCommitmentsRoute
  '/accounts/$slug/compare': typeof AccountsSlugCompareRoute
  '/accounts/$slug/import': typeof AccountsSlugImportRoute
  '/accounts/$slug': typeof AccountsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/pipeline': typeof PipelineRoute
  '/accounts/$slug': typeof AccountsSlugRouteWithChildren
  '/settings/llm': typeof SettingsLlmRoute
  '/accounts/$slug/ask': typeof AccountsSlugAskRoute
  '/accounts/$slug/commitments': typeof AccountsSlugCommitmentsRoute
  '/accounts/$slug/compare': typeof AccountsSlugCompareRoute
  '/accounts/$slug/import': typeof AccountsSlugImportRoute
  '/accounts/$slug/': typeof AccountsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integrations'
    | '/pipeline'
    | '/accounts/$slug'
    | '/settings/llm'
    | '/accounts/$slug/ask'
    | '/accounts/$slug/commitments'
    | '/accounts/$slug/compare'
    | '/accounts/$slug/import'
    | '/accounts/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integrations'
    | '/pipeline'
    | '/settings/llm'
    | '/accounts/$slug/ask'
    | '/accounts/$slug/commitments'
    | '/accounts/$slug/compare'
    | '/accounts/$slug/import'
    | '/accounts/$slug'
  id:
    | '__root__'
    | '/'
    | '/integrations'
    | '/pipeline'
    | '/accounts/$slug'
    | '/settings/llm'
    | '/accounts/$slug/ask'
    | '/accounts/$slug/commitments'
    | '/accounts/$slug/compare'
    | '/accounts/$slug/import'
    | '/accounts/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PipelineRoute: typeof PipelineRoute
  AccountsSlugRoute: typeof AccountsSlugRouteWithChildren
  SettingsLlmRoute: typeof SettingsLlmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$slug': {
      id: '/accounts/$slug'
      path: '/accounts/$slug'
      fullPath: '/accounts/$slug'
      preLoaderRoute: typeof AccountsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/llm': {
      id: '/settings/llm'
      path: '/settings/llm'
      fullPath: '/settings/llm'
      preLoaderRoute: typeof SettingsLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$slug/': {
      id: '/accounts/$slug/'
      path: '/'
      fullPath: '/accounts/$slug/'
      preLoaderRoute: typeof AccountsSlugIndexRouteImport
      parentRoute: typeof AccountsSlugRoute
    }
    '/accounts/$slug/ask': {
      id: '/accounts/$slug/ask'
      path: '/ask'
      fullPath: '/accounts/$slug/ask'
      preLoaderRoute: typeof AccountsSlugAskRouteImport
      parentRoute: typeof AccountsSlugRoute
    }
    '/accounts/$slug/commitments': {
      id: '/accounts/$slug/commitments'
      path: '/commitments'
      fullPath: '/accounts/$slug/commitments'
      preLoaderRoute: typeof AccountsSlugCommitmentsRouteImport
      parentRoute: typeof AccountsSlugRoute
    }
    '/accounts/$slug/compare': {
      id: '/accounts/$slug/compare'
      path: '/compare'
      fullPath: '/accounts/$slug/compare'
      preLoaderRoute: typeof AccountsSlugCompareRouteImport
      parentRoute: typeof AccountsSlugRoute
    }
    '/accounts/$slug/import': {
      id: '/accounts/$slug/import'
      path: '/import'
      fullPath: '/accounts/$slug/import'
      preLoaderRoute: typeof AccountsSlugImportRouteImport
      parentRoute: typeof AccountsSlugRoute
    }
  }
}

interface AccountsSlugRouteChildren {
  AccountsSlugAskRoute: typeof AccountsSlugAskRoute
  AccountsSlugCommitmentsRoute: typeof AccountsSlugCommitmentsRoute
  AccountsSlugCompareRoute: typeof AccountsSlugCompareRoute
  AccountsSlugImportRoute: typeof AccountsSlugImportRoute
  AccountsSlugIndexRoute: typeof AccountsSlugIndexRoute
}

const AccountsSlugRouteChildren: AccountsSlugRouteChildren = {
  AccountsSlugAskRoute: AccountsSlugAskRoute,
  AccountsSlugCommitmentsRoute: AccountsSlugCommitmentsRoute,
  AccountsSlugCompareRoute: AccountsSlugCompareRoute,
  AccountsSlugImportRoute: AccountsSlugImportRoute,
  AccountsSlugIndexRoute: AccountsSlugIndexRoute,
}

const AccountsSlugRouteWithChildren = AccountsSlugRoute._addFileChildren(
  AccountsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationsRoute: IntegrationsRoute,
  PipelineRoute: PipelineRoute,
  AccountsSlugRoute: AccountsSlugRouteWithChildren,
  SettingsLlmRoute: SettingsLlmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
